version: "3.8"
services:
  postgres:
    image: postgres:14
    env_file:
      - ./.env
    restart: always
    volumes:
      - ./init_db:/docker-entrypoint-initdb.d
      - autoria-pgdata:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    logging:
      options:
        max-size: 50m

volumes:
  autoria-pgdata:
    external: true